### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by kickerboy7** [cinquemb/WifiBruteCrack#1]
Can you give me a quick run to use this tool? Ive already install it, i just cant find a way to use it

**Comment by cinquemb** [comment]
If you don't know how to run a python script, you'll have much bigger problems that you need to solve first that I'm not sure I can help you with.

**Comment by XxsuperdeadlysniperxX** [comment]
Then why post the tool if you can't help

**Comment by cinquemb** [comment]
How much are you willing to pay for me to walk you through all the steps that you will probably have to do in order to get this running if you are having trouble with running a python script?

**Comment by XxsuperdeadlysniperxX** [comment]
Its that complicated?!

**Comment by cinquemb** [comment]
Not for me, and apparently not for others that came across this for ~8 years before you have, but maybe it is for you?

**Comment by Toni-d-e-v** [comment]
@XxsuperdeadlysniperxX  
Download lastest python
Download this script
open cmd in that folder
run python3 <scriptname.py>
thast it :)
