### ISSUE TITLE
does it work with windows

### ISSUE THREAD

**Issue by morpheuslord** [cinquemb/WifiBruteCrack#5]
I wanted to ask if this works with windows and what are all the resources like hardware if monitor mode required etc 
and I suggest you to have a better README explaining the various elements in your program

**Comment by XxsuperdeadlysniperxX** [comment]
This was made to work in windows

**Comment by morpheuslord** [comment]
well can you explain how does it work and how we can bruteforce active wifi in our local range and how fast is it

**Comment by XxsuperdeadlysniperxX** [comment]
@morpheuslord unfortunately i don't have a computer to try to help and i don't know how to code all i know is it was made on windows (cuz its more popular) or it could have been made useing linux (i don't know about this one) either way you'll have to figure it out yourself cuz im noy the creator of this program

**Comment by SunJ-Stars** [comment]
How is the cracking process? Is it similar to airtrack-ng?
